#pragma config(Hubs,  S1, HTServo,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     button1,        sensorTouch)
#pragma config(Sensor, S3,     button2,        sensorTouch)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C3_1,     leftFootA,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     leftFootB,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     rightFootA,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     rightFootB,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    leftShoulderA,        tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    leftShoulderB,        tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    leftElbow,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    head,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_1,    rightShoulderA,       tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    rightShoulderB,       tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    rightElbow,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * Project Name: MrRobot
 * Version: 1
**/

//// Include Files:
#include "JoystickDriver.c";

void initialize();



float deadzone(float power);

/// Joystick values:
float leftJoyY;
float rightJoyY;
float leftJoyX;

/// Variables for driveSwap, slowDown, and deadzone features:
float deadzoneValue  = 10;   // This is the joystick deadzone, which prevents motion when joystick returns to center
float slowDownFactor = 1;    // Speed multiplier
float joySwap = 1;           // Used to invert direction controls

task main()
{
   initialize();   // Run one-time initializations.


   while (true)
   {
      getJoystickSettings(joystick);

      if (!joystick.StopPgm && joystick.UserMode)
      {

         // Update joystick variables
         leftJoyY = joystick.joy1_y1;
         rightJoyY = joystick.joy1_y2;
         leftJoyX = joystick.joy1_x1;


         // Control drive motors
         motor[leftFootA] = (deadzone(leftJoyY/slowDownFactor)*joySwap);
         motor[leftFootB] = (deadzone(leftJoyY/slowDownFactor)*joySwap);
         motor[rightFootA] = (deadzone(rightJoyY/slowDownFactor)*joySwap);
         motor[rightFootB] = (deadzone(rightJoyY/slowDownFactor)*joySwap);


         // Servo control section
         servo[head] = leftJoyX + 127;

         if (joy1Btn(5)){
    				servo[leftShoulderA] += 1;
    				servo[leftShoulderB] -= 1;
    			} else {
    				servo[leftShoulderA] -= 1;
    				servo[leftShoulderB] += 1;
    			}

         if (joy1Btn(6)){
    				servo[rightShoulderA] += 1;
    				servo[rightShoulderB] -= 1;
    			} else {
    				servo[rightShoulderA] -= 1;
    				servo[rightShoulderB] += 1;
    			}

         if (joy1Btn(7)){
    				servo[leftElbow] += 1;
    			} else {
    				servo[leftElbow] -= 1;
    			}

         if (joy1Btn(8)){
    				servo[rightElbow] += 1;
    			} else {
    				servo[rightElbow] -= 1;
    			}
      }
   }
}

void initialize()
{
}

float deadzone(float power) {
   if (abs(power) < deadzoneValue) {
      return 0;
   } else {
      return power;
   }
}
